<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CoffeeIcon.ico</ApplicationIcon>
    <Version>0.2.1</Version>
    <FileVersion>0.2.1</FileVersion>
    <AssemblyVersion>0.2.1</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SPTCoffee.Contracts\SPTCoffee.Contracts.csproj"
                      SetTargetFramework="TargetFramework=net8.0"
                      GlobalPropertiesToRemove="RuntimeIdentifier;SelfContained;PublishSingleFile;PublishTrimmed" />
  </ItemGroup>

</Project>
